package com.oknion.conceptmap.Model;

// Generated Dec 18, 2014 9:52:00 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CcrelationshipPoints generated by hbm2java
 */
@Entity
@Table(name = "ccrelationship_points")
public class CcrelationshipPoints implements java.io.Serializable {

	private Integer id;
	private Ccrelationship ccrelationship;
	private Double points;
	private Integer orders;

	public CcrelationshipPoints() {
	}

	public CcrelationshipPoints(Integer id, Ccrelationship ccrelationship) {
		this.id = id;
		this.ccrelationship = ccrelationship;
	}

	public CcrelationshipPoints(Integer id, Ccrelationship ccrelationship,
			Double points) {
		this.id = id;
		this.ccrelationship = ccrelationship;
		this.points = points;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ccrelaPointId", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ccrelationship_ccrelaId", nullable = false)
	public Ccrelationship getCcrelationship() {
		return this.ccrelationship;
	}

	public void setCcrelationship(Ccrelationship ccrelationship) {
		this.ccrelationship = ccrelationship;
	}

	@Column(name = "points")
	public Double getPoints() {
		return this.points;
	}

	public void setPoints(Double points) {
		this.points = points;
	}

	@Column(name = "orders")
	public Integer getOrders() {
		return orders;
	}

	public void setOrders(Integer orders) {
		this.orders = orders;
	}

}
