package com.oknion.conceptmap.Model;

// Generated Oct 21, 2014 3:41:47 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Classes generated by hbm2java
 */

@Entity
@Table(name = "classes")
public class Classes implements java.io.Serializable {

	private String classId;
	private String className;
	private Set<User> users = new HashSet<User>(0);

	public Classes() {
	}

	public Classes(String classId, String className) {
		this.classId = classId;
		this.className = className;
	}

	public Classes(String classId, String className, Set<User> users) {
		this.classId = classId;
		this.className = className;
		this.users = users;
	}

	@Id
	@Column(name = "classId", unique = true, nullable = false, length = 10)
	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	@Column(name = "className", nullable = false, length = 50)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
	@Cascade({ CascadeType.ALL })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
