package com.oknion.conceptmap.Model;

// Generated Oct 23, 2014 5:52:22 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

//import org.codehaus.jackson.annotate.JsonIgnore;
//import org.codehaus.jackson.annotate.JsonProperty;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Concept generated by hbm2java
 */
@Entity
@Table(name = "concept")
public class Concept implements java.io.Serializable {

	private Integer ccId;
	private Conceptmap conceptmap;
	private String loc;
	private String ccName;
	private Double keyId;
	private String ccText;
	private Set<Document> documents = new HashSet<Document>(0);
	public boolean checked = false;

	public Concept() {
	}

	public Concept(Conceptmap conceptmap) {
		this.conceptmap = conceptmap;
	}

	public Concept(Conceptmap conceptmap, String loc, String ccName,
			Double keyId, String ccText, Set<Document> documents) {
		this.conceptmap = conceptmap;
		this.loc = loc;
		this.ccName = ccName;
		this.keyId = keyId;
		this.ccText = ccText;
		this.documents = documents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ccId", unique = true, nullable = false)
	@JsonIgnore
	public Integer getCcId() {
		return this.ccId;
	}

	public void setCcId(Integer ccId) {
		this.ccId = ccId;
	}

	@ManyToOne
	@JoinColumn(name = "cmID", nullable = false)
	@JsonIgnore
	public Conceptmap getConceptmap() {
		return this.conceptmap;
	}

	public void setConceptmap(Conceptmap conceptmap) {
		this.conceptmap = conceptmap;
	}

	@Column(name = "loc", length = 50)
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	@Column(name = "ccName", length = 50)
	@JsonProperty("ccName")
	public String getCcName() {
		return this.ccName;
	}

	public void setCcName(String ccName) {
		this.ccName = ccName;
	}

	@Column(name = "keyId", precision = 22, scale = 0)
	@JsonProperty("key")
	public Double getKeyId() {
		return this.keyId;
	}

	public void setKeyId(Double keyId) {
		this.keyId = keyId;
	}

	@Column(name = "ccText", length = 100)
	@JsonProperty("text")
	public String getCcText() {
		return this.ccText;
	}

	public void setCcText(String ccText) {
		this.ccText = ccText;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concept")
	@JsonIgnore
	@Cascade({ CascadeType.ALL,
			org.hibernate.annotations.CascadeType.DELETE_ORPHAN })
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

}
