package com.oknion.conceptmap.Model;

// Generated Oct 21, 2014 3:41:47 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification")
public class Notification implements java.io.Serializable {

	private String notiId;
	private User user;
	private String content;
	private Date dateReceive;
	private boolean isRead;
	private String name;

	public Notification() {
	}

	public Notification(String notiId, User user, String content,
			Date dateReceive, boolean isRead, String name) {
		this.notiId = notiId;
		this.user = user;
		this.content = content;
		this.dateReceive = dateReceive;
		this.isRead = isRead;
		this.name = name;
	}

	@Id
	@Column(name = "notiId", unique = true, nullable = false, length = 10)
	public String getNotiId() {
		return this.notiId;
	}

	public void setNotiId(String notiId) {
		this.notiId = notiId;
	}

	@ManyToOne()
	@JoinColumn(name = "userId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateReceive", nullable = false, length = 19)
	public Date getDateReceive() {
		return this.dateReceive;
	}

	public void setDateReceive(Date dateReceive) {
		this.dateReceive = dateReceive;
	}

	@Column(name = "isRead", nullable = false)
	public boolean isIsRead() {
		return this.isRead;
	}

	public void setIsRead(boolean isRead) {
		this.isRead = isRead;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
