package com.oknion.conceptmap.Model;

// Generated Oct 21, 2014 3:41:47 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sharewith generated by hbm2java
 */
@Entity
@Table(name = "sharewith")
public class Sharewith implements java.io.Serializable {

	private Integer sharewithId;
	private User user;
	private Conceptmap conceptmap;
	private Date shareDate;

	public Sharewith() {
	}

	public Sharewith(User user, Conceptmap conceptmap) {
		this.user = user;
		this.conceptmap = conceptmap;
	}

	public Sharewith(User user, Conceptmap conceptmap, Date shareDate) {
		this.user = user;
		this.conceptmap = conceptmap;
		this.shareDate = shareDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sharewithId", unique = true, nullable = false)
	public Integer getSharewithId() {
		return this.sharewithId;
	}

	public void setSharewithId(Integer sharewithId) {
		this.sharewithId = sharewithId;
	}

	@ManyToOne
	@JoinColumn(name = "shareUId", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne
	@JoinColumn(name = "shareCmID", nullable = false)
	public Conceptmap getConceptmap() {
		return this.conceptmap;
	}

	public void setConceptmap(Conceptmap conceptmap) {
		this.conceptmap = conceptmap;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shareDate", length = 19)
	public Date getShareDate() {
		return this.shareDate;
	}

	public void setShareDate(Date shareDate) {
		this.shareDate = shareDate;
	}

}
